import type { Metadata } from "next";
import { Mukta } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster";
import DesignerContextProvider from "@/context/DesignerContex";
const outfit = Mukta({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700", "800",] });
import NextTopLoader from 'nextjs-toploader'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <NextTopLoader color="#fff"
            showSpinner={false}
            easing="ease" />
          <DesignerContextProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster />
            </ThemeProvider>
          </DesignerContextProvider>
        </body>
      </html >
    </ClerkProvider>
  );
}
